### ISSUE TITLE
Async handlers

### ISSUE THREAD

**Issue by valdisiljuconoks** [NimaAra/Easy.MessageHub#21]
Hi,

Thanks for the library, it's great addition to our system. However, I was wondering - what do you think of adding support for async handlers?

We have subscription handler where we need to call async methods. Could wrap of course in some `GetAwaiter` magic, but was wondering about "native" support from the hub side.

Any pointers whether this could be complex to add? Probably can contrib if you give some heads up ideas.

Thanks!

**Comment by NimaAra** [comment]
Hi,

I had intentionally not included support for asynchronous handlers as `Task`s. This is by design as hub's only responsibility is to raise the events as they come in (fire and forget) it should not `await` for subscribers to finish processing them.

I would suggest (depending on your use-case) to consume your events by adding them to a pub/sub queue (think `System.Threading.Channels` or `BlockingCollection<T>`) which fits naturally with the _producer/consumer_ pattern.

Alternatively, it is acceptable to use `async void` for cases where you need to `await` inside your handlers (see [THIS](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming), [THIS](https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Tip-1-Async-void-is-for-top-level-event-handlers-only) and [THIS](https://stackoverflow.com/questions/19415646/should-i-avoid-async-void-event-handlers)).

HTH.

**Comment by valdisiljuconoks** [comment]
Thx, think we will pump into a channel then.
