### ISSUE TITLE
Publish and subscribe from different threads

### ISSUE THREAD

**Issue by lrhage** [NimaAra/Easy.MessageHub#9]
Hi! I need to subscribe from the UI thread and update controls. Is there a way to "subscribe on current thread"? I know that I can use SynchronizationContext (I'm using WinForms) but that's mean to change a lot of code.

Thanks!

**Comment by NimaAra** [comment]
Hi,

While the library is tread-safe in the sense that you can publish and subscribe from different threads, it does not handle UI-synchronization for the user. This was done intentionally so that the user can choose the best marshalling strategy.

As you mentioned, `SynchronizationContext` is the way to go.

**Comment by desarrollo03TR** [comment]
Thanks!
